[profile.default]
auto_detect_solc = true
optimizer = true
optimizer_runs = 200
via_ir = false
# debug revert strings looks experimental and fails the CI because of an unexpected error.
revert_strings = "default"
names = true
sizes = true

[profile.default.fuzz]
runs = 1024

[profile.production.fuzz]
runs = 256

[profile.common]
test = "test/common"

[profile.compound]
# fork_block_number = 15_581_371 # eth
# fork_block_number = 24_128_078 # bsc
#fork_block_number = 0 # local

[profile.aave-v2]
fork_block_number = 15_581_371 # Block number when the Aave's V2 IRM was updated for the stETH.
